"""Added uuid_hash column to User model

Revision ID: 1a269eafff3a
Revises: 
Create Date: 2023-10-09 21:03:54.596099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a269eafff3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_hash', sa.BigInteger(), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid_hash')

    # ### end Alembic commands ###
