"""Added MoodTracker table

Revision ID: 817d5774084e
Revises: 1a269eafff3a
Create Date: 2023-10-10 16:46:40.636949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817d5774084e'
down_revision = '1a269eafff3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood_tracker')
    # ### end Alembic commands ###
